### ISSUE TITLE
Edit session block: Inherited Location or Room info persists even if "Inherit from parent event" is unticked

### ISSUE THREAD

**Issue by shesselbach** [indico/indico#2075] opened 2015-09-30 14:01 UTC
If in a session block **Inherit from parent event** is ticked (default for new sessions) and then in **Basic edit** the tick is removed the text in the fields *Location* and *Room* disappears.  The user might now think that the fields are cleared. However, after pressing *Save* the inherited text reappears in the timetable. The inherited info can only be removed by adding e.g. some whitespace. This is not intuitive and should be improved.

If new text is entered for both *Location* and *Room* everything is fine. Only if one or both fields are supposed to be cleared this problem shows up.

This issue has been reported by a user of our site and I reproduced it on http://indico-sandbox.cern.ch

**Comment by ThiefMaster** [comment] 2015-09-30 14:02
Possible duplicate of #1909 (indico-sandbox is *very* outdated)

**Comment by ThiefMaster** [comment] 2016-07-20 09:07
Obsolete since v1.9.7

**Closed by ThiefMaster** 2016-07-20 09:07 UTC
