### ISSUE TITLE
Show the real target URL on hover for "link"-type materials

### ISSUE THREAD

**Issue by mariadimou** [indico/indico#4261] opened 2020-01-27 13:54 UTC
**Is your feature request related to a problem? Please describe.**

_I'm always frustrated when I have a lot of different materials attached to a given contribution and while pointing with the mouse, I see: `https://indico.cern.ch/event/.../contributions/.../attachments/.../.../go`_

**Describe the solution you'd like**

_I'd like to see the actual destination URL (when the material is a link)._

**Describe alternatives you've considered**

_I have no alternative but I have an argument in favour of my request. If the event gets 'hacked' malicious links could replace the original one, which could embarrassing and/or dangerous._

**Additional context**

_Happy to, if anything is unclear..._

**Comment by ThiefMaster** [comment] 2020-01-27 13:56
I fully agree that seeing the destination link would be nice. The reason why I didn't show it originally when implementing this was to avoid disclosing the target in case the material is marked as restricted and you cannot access it (but still see the restricted attachment).

But maybe we can either perform the access check or show the target only if the attachment or its folder doesn't have any special protection.

**Comment by ThiefMaster** [comment] 2020-03-09 21:14
duplicate of #2599 (but keeping it open since the other one is buried deep within ancient issues)

**Closed** 2020-11-11 14:55 UTC
Labels: duplicate, enhancement

**Comment by ThiefMaster** [comment] 2020-11-11 14:57
closed this one as a duplicate since the other (and older) issue is now on the 3.0 milestone and project board

**Comment by ThiefMaster** [comment] 2020-11-24 13:17
FYI, this is done in #4718 (and will be deployed to cern indico soon-ish, probably during one of the next days)
