### ISSUE TITLE
locale_name not set for users created in backend

### ISSUE THREAD

**Issue by Problemkerze** [indico/indico#3015] opened 2017-07-20 13:55 UTC
For users created in the backend, no locale_name seems to be specified.
At login after entering access data, the user gets the error
> Could not build url for endpint 'assets i8n_locale'. Did you forget to specify values ['locale_name']?

After changing (as an admin) something in the User's Profile/Preferences, the error is gone.

**Comment by ThiefMaster** [comment] 2017-07-20 14:05
Duplicate of #3001 which was fixed in d74e87e00 and will be in 1.9.11.dev13 which will most likely be released on PyPI today or tomorrow.

I guess with "created in the backend" you mean "create user" in the admin area? We indeed don't set any default settings there which is something that will be fixed too.

**Closed by ThiefMaster** 2017-07-20 14:05 UTC
Labels: bug, duplicate

**Comment by Problemkerze** [comment] 2017-07-20 14:10
correct, in my mind the admin area is called backend :)
