### ISSUE TITLE
Email errors

### ISSUE THREAD

**Issue by alscheuring** [indico/indico#4690] opened 2020-10-30 13:13 UTC
Hi, I started getting this logging email:

2020-10-30 05:48:23,718  0000000000000000  indico.emails - ERROR emails.py:52 -- Could not send email "[Indico] Registration for AI-driven discovery in Biophysics" (attempt 10/10); giving up [(550, '5.7.1 <noreply@cmu.edu>... Sender rejected', u'noreply@cmu.edu')]; stored data in /opt/indico/tmp/failed-email-2020-10-30-m_jzS_

This seems to only happen for registration emails. It sends password reminders just fine so the email settings generally work. I don't see any settings in the event itself that might cause this but maybe someone knows what I'm missing?

Server default language (en_GB)
Indico version installed (2.3.1)
Python version used (2.7.17)
Postgres version used (10.0.14)
Operating system used (Linux Ubuntu 18.04)
Debug mode (disabled)
Basic statistics (number of events, contributions and users)

My conf:

```python
# Email settings
SMTP_SERVER = ('my college smtp relay', 587)
SMTP_USE_TLS = True
#SMTP_LOGIN = ''
#SMTP_PASSWORD = ''
SUPPORT_EMAIL = 'myemail@cmu.edu'
PUBLIC_SUPPORT_EMAIL = 'myemail@cmu.edu'
NO_REPLY_EMAIL = 'myemail@cmu.edu'
SMTP_TIMEOUT = 60
```

**Comment by ThiefMaster** [comment] 2020-10-30 13:17
You need to use a mail server that does not restrict your sender addresses. It looks like you are not authorized to send from `noreply@cmu.edu`.

Best option is to contact whoever runs your mail infrastructure and see whether they provide anything for this.

Closing the issue since it's not a bug in indico (and this type of question would be more suitable for the [forum](https://talk.getindico.io)).

**Closed by ThiefMaster** 2020-10-30 13:17 UTC

**Comment by alscheuring** [comment] 2020-10-30 15:04
But why is it sending with the email address 'noreply@cmu.edu' when I specifically told it not to?

 My conf file actually originally had "alsemail@andrew.cmu.edu" for all the options but 'noreply@cmu.edu' was still being used.

**Comment by ThiefMaster** [comment] 2020-10-30 15:26
In some places in an event the sender address can be customized; this may be the case here... In case of registration forms that's the "Notification sender address" in the general settings of the registration form.

**Comment by alscheuring** [comment] 2020-10-30 15:32
Oh snap. There it is right there.  THANK YOU
