### ISSUE TITLE
Allow specifying hours and minutes at the same time in duration fields

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#2645] opened 2016-10-13 14:38 UTC
Related SNOW ticket `CHG34429`.

**Comment by ThiefMaster** [comment] 2016-10-13 14:40
We might already have an issue about improving this. Or it was just an 
asana task at some point, dunno.

**Comment by pferreir** [comment] 2018-03-26 08:00
Duplicate of #2462

**Closed by pferreir** 2018-03-26 08:00 UTC
Labels: enhancement
