### ISSUE TITLE
cannot display timetable

### ISSUE THREAD

**Issue by MariamNsubuga** [indico/indico#4826] opened 2021-03-17 09:11 UTC
i have created a meeting  unfortunately it does not display the timetable. it displays a black page. even for conference events timetables cannot be displayed.

**Comment by ThiefMaster** [comment] 2021-03-17 09:11
That sounds more like a problem with your browser... Do you have a link to it? Any errors in the JS console?

**Comment by MariamNsubuga** [comment] 2021-03-17 09:18
no errors in JS console

**Comment by ThiefMaster** [comment] 2021-03-17 09:20
Well without any details nor a link to the instance to see it ourselves there's not much we can do.... Which browser are you using?

**Comment by MariamNsubuga** [comment] 2021-03-17 09:51
![indico timetable](https://user-images.githubusercontent.com/30923697/111448427-744ef680-871f-11eb-9b80-51940104434a.png)

thats what i get

**Comment by ThiefMaster** [comment] 2021-03-17 09:53
That shouldn't happen for sure. What about my other question ("Which browser are you using?")?

Also, which Indico version are you using and if the indico instance is accessible from the internet please post a link to your event.

**Comment by MariamNsubuga** [comment] 2021-03-17 09:53
when a user clicks on the change theme to other style apart from indico style they can  see it

**Comment by MariamNsubuga** [comment] 2021-03-17 09:57
i am using chrome. tested with firefox.

**Comment by ThiefMaster** [comment] 2021-03-17 09:57
Please answer my questions... otherwise we really cannot help you.

**Comment by ThiefMaster** [comment] 2021-03-17 10:01
Which browser version?

Is your instance accessible on the internet?

**Comment by MariamNsubuga** [comment] 2021-03-17 10:06
chrome 89, firefox  86
how can i check for indico's version?

**Comment by ThiefMaster** [comment] 2021-03-17 10:08
In recent versions it's shown in the footer:

![image](https://user-images.githubusercontent.com/179599/111450838-13b8bd00-8711-11eb-8e58-58781f197994.png)

Otherwise open `https://yourindicohost/system-info`; and check the `indico_version` value there.

**Comment by MariamNsubuga** [comment] 2021-03-17 10:38
indico version 2.2.8

**Comment by ThiefMaster** [comment] 2021-03-17 10:44
That version is outdated (please upgrade to v2.3.4), but we are not aware of the problem you have in any 2.x version.

So I think unless you can share the URL to your indico instance (ideally the event where it happens) there's nothing we can do here...

**Comment by MariamNsubuga** [comment] 2021-03-17 10:52
but it was working well since yesterday until today morning.

**Comment by ThiefMaster** [comment] 2021-03-17 10:53
Is it only happening in this particular event? Or in all events?

**Comment by MariamNsubuga** [comment] 2021-03-17 10:56
all events but when a user selects other style apart from indico style they
can see it.

**Comment by ThiefMaster** [comment] 2021-03-17 10:58
Did you make any changes on the server?

And unless your instance is behind a firewall, can you please share the link to it?

**Comment by MariamNsubuga** [comment] 2021-03-17 11:03
yes the server is behind a firewall.
i did some changes in the meeting.html:  /indico/modules/events/templates/display/indico/meeting.html
the aim was to make the meeting event type to have a logo next to the title.  i wanted to customize the meeting event to be similar to conference

**Comment by ThiefMaster** [comment] 2021-03-17 11:10
...and you didn't consider this relevant information to provide from the beginning? :)

Most likely your change caused this problem. Please revert it (just upgrading Indico is the easiest way since such changes are lost during an upgrade anyway).

If you want to make changes to a template, you should ideally use the [template customization feature](https://docs.getindico.io/en/stable/config/settings/#customization). While that's of course still fragile during updates especially in case of templates where changing some blocks is not sufficient, it at least avoids modifying the core indico files, and lets you easily undo changes (by just deleting the override file).

In any case, this is clearly not a bug in Indico itself so I'm closing this issue; I'd recommend using our [forum](https://talk.getindico.io) if you have any followup questions on using the customization functionality...

**Closed by ThiefMaster** 2021-03-17 11:10 UTC
Labels: norepro

**Comment by MariamNsubuga** [comment] 2021-03-17 11:21
the link to the event is [here](https://events.renu.ac.ug/event/23/)

**Comment by ThiefMaster** [comment] 2021-03-17 11:23
```html
<div class="main"><div>
    <div class="conference-page"
         >
        
        <div class="page-content">
            
        </div>
    </div>
</div></div>
```

the page-content is completely empty so I'm quite sure this is related to the changes you made to the templates.

**Comment by MariamNsubuga** [comment] 2021-03-17 11:25
but i replace the meeting.html file with the one on  indico github.

**Comment by ThiefMaster** [comment] 2021-03-17 11:28
Did you restart/reload the uwsgi service?

Also, did you use the file from the `2.3-maintenance` branch? Not sure if we changed something in that file in master, but using a file from the wrong version could cause problems for sure.

So I'd strongly suggest to upgrade to 2.3.4 first since this will already undo any manual changes to the code.

**Comment by MariamNsubuga** [comment] 2021-03-17 11:32
no just restart indico-celery.service and apache2
no i did use the file form 2.3 maintenance branch

**Comment by MariamNsubuga** [comment] 2021-03-17 11:33
i used afile from the  master branch

**Comment by ThiefMaster** [comment] 2021-03-17 11:35
uwsgi is the important one. apache never needs to be restarted unless you edit the apache config, and indico-celery is only handling background tasks so while it should be restarted together with uwsgi when making code changes, it's not really important here - the webapp is handled by uwsgi.

**Comment by MariamNsubuga** [comment] 2021-03-17 12:18
how can i do the upgrade, are there defined steps.

**Comment by ThiefMaster** [comment] 2021-03-17 12:27
Have you checked the [documentation](https://docs.getindico.io/en/stable/installation/upgrade/)? ;)

**Comment by MariamNsubuga** [comment] 2021-03-17 14:19
Thanks

**Comment by MariamNsubuga** [comment] 2021-03-17 14:38
Is there a way of adding a logo on the event type of meeting?

**Comment by ThiefMaster** [comment] 2021-03-17 14:41
No, unless you create a custom meeting theme using a plugin. This is what we do on CERN Indico for example: https://github.com/indico/indico-plugins-cern/tree/2.3-maintenance/themes_cern
