### ISSUE TITLE
Migration from 0.97 to 1.2 problems

### ISSUE THREAD

**Issue by albertocrj** [indico/indico#1808] opened 2015-03-23 21:10 UTC
Hello all,

I'm trying to upgrade from 0.97 version to 1.2 and i'm getting this error:
python /opt/indico/bin/migration/migrate.py  --prev-version 0.97

```=============================================================================
This script will migrate your Indico DB to a new version. We recommend that
this operation be executed while the web server is down, in order to avoid
concurrency problems and DB conflicts.


Are you sure you want to execute the migration now? [y/N] y

Executing migration...

Probing DB connection... DONE!

Adding new plugins and adapting existing ones to new name policies (0.98b2)
  DONE

Reloading all plugins (0.97)
  DONE

Fixing AccessController for categories (0.98b)
  DONE

Adding missing attributes to conference objects and children (0.98b2)
  DONE63 97.546012%] 89 Reunião do projeto RedeH - Futura RNP - Grupo 3          

Migrating database tasks from the old format to the new one (0.98b)

Migration failed! DB may be in  an inconsistent state:
Traceback (most recent call last):
  File "/opt/indico/bin/migration/migrate.py", line 1086, in main
    dry_run=args.dry_run)
  File "/opt/indico/bin/migration/migrate.py", line 1032, in runMigration
    task(dbi, withRBDB, prevVersion)
  File "/opt/indico/bin/migration/migrate.py", line 295, in taskMigration
    for t in HelperTaskList().getTaskListInstance().getTasks():
  File "/usr/local/lib/python2.7/dist-packages/indico-1.2-py2.7.egg/MaKaC/common/timerExec.py", line 270, in getTaskListInstance
    dbmgr = DBMgr.getInstance()

NameError: global name 'DBMgr' is not defined
=============================================================================
```

Any clues?

**Comment by pferreir** [comment] 2015-03-25 17:29
0.97 to 1.2 is a bit of a violent change, but in any case this is caused by a bug.

I would suggest that you directly edit `/usr/local/lib/python2.7/dist-packages/indico-1.2-py2.7.egg/MaKaC/common/timerExec.py` and change this:

https://github.com/pferreir/indico/compare/v1.2...fix-1.2-DBMgr-import

Please let us know how it goes.

**Comment by albertocrj** [comment] 2015-03-25 18:10
Hi,
Seems to be fixed, but I'm getting a new error:

This script will migrate your Indico DB to a new version. We recommend that
this operation be executed while the web server is down, in order to avoid
concurrency problems and DB conflicts.


Are you sure you want to execute the migration now? [y/N] y

Executing migration...

Probing DB connection... DONE!

Adding new plugins and adapting existing ones to new name policies (0.98b2)
  DONE

Reloading all plugins (0.97)
  DONE

Fixing AccessController for categories (0.98b)
  DONE

Adding missing attributes to conference objects and children (0.98b2)

  DONE63 97.546012%] 89 Reunião do projeto RedeH - Futura RNP - Grupo 3

Migrating database tasks from the old format to the new one (0.98b)
   * StatisticsUpdater
  DONE

Replacing the conference dictionary in the Category objects by a OOTreeSet. (0.98b)
  DONE

Replacing category date indexes. (0.98b)
  DONE

Create category date index without visibility. (0.98.1)
  DONE

# Initializing/updating index catalog (0.98b)
  DONE

Initializing room blocking indexes. (0.98b2)
  DONE

Initializing room+day => reservation index. (0.98.1)
  DONE

Migrate the reservation notification system. (0.98-rc2)
  DONE

Replacing en_US with en_GB. (0.98b2)
  DONE

Installing new TPLs for meeting/lecture styles (0.98b2)
  DONE

Modifying Room GUIDs (0.98b2)
  DONE

Add missing location info to slots of a session that contains location or room (0.98.1)
  DONE63 97.546012%] 89 Reunião do projeto RedeH - Futura RNP - Grupo 3

Creating new "All Requests" index (0.98.3)

Migration failed! DB may be in  an inconsistent state:
Traceback (most recent call last):
  File "/opt/indico/bin/migration/migrate.py", line 1086, in main
    dry_run=args.dry_run)
  File "/opt/indico/bin/migration/migrate.py", line 1032, in runMigration
    task(dbi, withRBDB, prevVersion)
  File "/opt/indico/bin/migration/migrate.py", line 532, in collaborationRequestIndexCreate
    ci = IndexesHolder().getById('collaboration')
  File "/usr/local/lib/python2.7/dist-packages/indico-1.2-py2.7.egg/MaKaC/common/indexes.py", line 1344, in getById
    return Idx[str(id)]
KeyError: 'collaboration'

**Comment by pferreir** [comment] 2015-03-26 17:19
This issue has already been fixed in the 1.2 branch. Please try to use the 1.2.1rc1 egg. You can resume the migration (after installing the egg and doing `indico_initial_setup --existing-config=/opt/indico/etc/indico.conf`):

```console
$ python /opt/indico/bin/migrate.py --run-from=collaborationRequestIndexCreate --prev-version=0.97
```

**Comment by pferreir** [comment] 2015-03-31 09:42
Closing for now, as this is most likely the solution. Please reopen if needed.

**Closed by pferreir** 2015-03-31 09:42 UTC
Labels: bug, infoneeded, p-medium

**Comment by albertocrj** [comment] 2015-06-17 18:19
Hi man,


I was able to migrate my database, but if I try to create a new meeting or edit an existing one, I get the following error:

=======================================================
exception message => 'clara'
exception type => <type 'exceptions.KeyError'>
traceback => 
  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/webinterface/rh/base.py", line 523, in process
    res = self._process()

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/webinterface/rh/conferenceModif.py", line 120, in _process
    return p.display(**pars)

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/webinterface/pages/base.py", line 206, in display
    self._display( params ), \

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/webinterface/pages/main.py", line 155, in _display
    body = WMainBase(self._getBody( params ), self._timezone, self._getNavigationDrawer(),

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/webinterface/pages/conferences.py", line 1557, in _getBody
    return self._applyFrame( self._getPageContent( params ) )

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/webinterface/meeting.py", line 579, in _getPageContent
    return wc.getHTML( pars )

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/webinterface/wcomponents.py", line 202, in getHTML
    tempHTML = templateEngine.render(self.tplFile, vars, self)

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/common/TemplateExec.py", line 136, in render
    return template.render(**params)

  File "/usr/local/lib/python2.7/dist-packages/Mako-0.9.1-py2.7.egg/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)

  File "/usr/local/lib/python2.7/dist-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 807, in _render
    **_kwargs_for_callable(callable_, data))

  File "/usr/local/lib/python2.7/dist-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 839, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)

  File "/usr/local/lib/python2.7/dist-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 865, in _exec_template
    callable_(context, *args, **kwargs)

  File "/opt/indico/tmp/mako_modules/MConfModifMainData.tpl.py", line 30, in render_body
    runtime._include_file(context, 'EventModifMainData.tpl', _template_uri, evtType='meeting', confObj=self_._conf)

  File "/usr/local/lib/python2.7/dist-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 734, in _include_file
    callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))

  File "/opt/indico/tmp/mako_modules/EventModifMainData.tpl.py", line 251, in render_body
    styleOptions = info.HelperMaKaCInfo.getMaKaCInfoInstance().getStyleManager().getStyleDictForEventType(confObj.getType())

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/common/info.py", line 641, in getStyleDictForEventType
    return dict((styleID, styles[styleID]) for styleID in self._eventStylesheets.get(type, []))

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/common/info.py", line 641, in <genexpr>
    return dict((styleID, styles[styleID]) for styleID in self._eventStylesheets.get(type, []))

request handler => MaKaC.webinterface.rh.conferenceModif.RHConferenceModification
url => https://homolog2-indico.local/event/222/manage/general/
parameters => 
confId = 222
headers => 
Cookie: _saml_idp=aHR0cHM6Ly9pZHAucm5wLmJyL2lkcC9zaGliYm9sZXRo; indico_session=106ca800-470f-4277-b43f-fd40525bafc3
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0
Connection: keep-alive
Referer: https://homolog2-indico.local/event/222/
Host: homolog2-indico.local
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
user => [0] ADMINISTRADOR, Administrador <admin@localhost>
=======================================================

With a new fresh database everything works fine.


Thanks

Alberto Viana

**Comment by pferreir** [comment] 2015-06-18 13:16
This looks like an unrelated issue. Are you by any change customizing your event stylesheets in `indico.conf`? It looks like there's a stylesheet called `clara` that not exist in the database.

**Comment by albertocrj** [comment] 2015-06-18 18:08
Hi,
you're right, I imported the stylesheet "clara" and everything seems to work fine now, but one last question:
Why this happen even with new meetings? I did not set this as default (double checked in "server admin" -> "Layout" -> "Timetable Styles" and in indico.conf) and I'm not sure why it's using it.

Really appreciate your help.

Thanks 
Alberto Viana
