### ISSUE TITLE
Permissions on Sub-contributions don't seem right

### ISSUE THREAD

**Issue by dguest** [indico/indico#3428] opened 2018-06-25 15:14 UTC
When I create an event with several contributions, I am able to give people access to upload material to their their contribution by adding them as speakers. The thing that confuses me is that when I create "subcontributions" and add the same people as speakers, they don't get permission to upload material, on the subcontribution or anywhere else. 

The only work around is to make them a speaker on the whole contribution. Is this intended?

**Comment by pferreir** [comment] 2018-06-25 15:17
I believe this is a duplicate of #2363. Please reopen if otherwise.

**Comment by ThiefMaster** [comment] 2018-06-25 15:17
Hi, subcontributions don't have ACLs at se moment. As you noticed, the one of the contribution is used there.

Duplicate of #2363

**Closed** 2018-06-25 15:17 UTC
