### ISSUE TITLE
show the actual URL when attached material is a link

### ISSUE THREAD

**Issue by mariadimou** [indico/indico#3489] opened 2018-08-08 14:35 UTC
I discussed this suggestion with Pedro: 
Example: https://indico.cern.ch/event/610411/ contains a link amongst materials. 
The link shows https://indico.cern.ch/event/610411/attachments/1428701/2211887/go

The user doesn't know what this is before clicking. Wouldn't it be more functional and secure that one can see the actual URL when placing the mouse on such material entries?

Thank you very much for considering this.

Yours
Maria

**Comment by ThiefMaster** [comment] 2018-08-08 14:39
Generally I agree with you - seeing the target URL would be much nicer.

The reason why we added the redirector there is so we can check if the user actually has access to the material without having to do that for every link that's attached to the event. But maybe having protected link attachments is uncommon enough.. would have to check the DB for that.

**Comment by ThiefMaster** [comment] 2020-11-11 14:39
duplicate of #4261

**Closed by ThiefMaster** 2020-11-11 14:39 UTC
Labels: duplicate
