### ISSUE TITLE
Registration statistics

### ISSUE THREAD

**Issue by cohm** [indico/indico#3466] opened 2018-07-20 12:34 UTC
I organized the yearky Supersymmetry workshop for the ATLAS experiment in Stockholm a few months ago, and I am trying to generate some stats about the participants, i.e. what countries/continents and institutes they come from. Is there a way to do this in indico? I can't find an option for it, but that doesn't necessarily mean it doesn't exist. If it doesn't exist yet, perhaps it could be implemented for the future? I think many would appreciate a possibility to summarize an event in this way, for example to to outsiders who participated!

Many thanks!

Best,
Christian

**Comment by ThiefMaster** [comment] 2018-07-20 12:36
You could export all registrations as CSV/XLSX and then use a custom tool or e.g. Excel to generate any stats you want.

We also do have some builtin stats such as "registrants per country" - but of course that won't contain continents, institutes, etc.

**Comment by cohm** [comment] 2018-07-20 12:53
Thanks for the quick reply! I did something similar already, but it doesn't exactly work well (could be because we seem to not have had the "country" activated during registration):

~/Downloads > cat registrations.csv | cut -d "," -f 5 | cut -d "(" -f 2 | cut -d ")" -f 1 | sort | uniq
"LPNHE-Paris
"Max-Planck-Institut fur Physik
"Universita e INFN
"University and INFN
AU
Affiliation
CA
CERN
CH
CN
DE
DK
ES
FR
GB
IFIC Valencia
IHEP
INFN-Genova
IT
JP
LBNL
LBNL / University of Oregon
NL
NO
RO
RS
SE
US
University of Adelaide
University of Oxford
University of Sheffield

(Here I was trying to filter out the country code in parentheses after the institute name)

Adding a 'wc -l' at the end then gives the number, but you can't see it doesn't work quite as easily as I hoped.

Where can I find the "registrants per country" option?

**Comment by ThiefMaster** [comment] 2018-07-20 12:56
When viewing the dashboard for a registration form in the management area there's a "stats" button. But if you didn't ask your registrant for the country, you won't be able to get anything useful there either.

**Comment by cohm** [comment] 2018-07-20 13:11
Thanks. I don't find it, but it could very well be because the instance we use in ATLAS is using an older version (most things don't match the online manual I found through googling, so I guess things change quite rapidly). I can't actually easily see what version of indico we're using (the main one that the CERN experiments are using) - how do I do that? Sorry for the naive question and thanks for the quick replies!

**Comment by ThiefMaster** [comment] 2018-07-20 13:14
![image](https://user-images.githubusercontent.com/179599/43004258-7297b4f0-8c2f-11e8-99bf-2f0a8354b61a.png)

indico.cern.ch is using 2.1, if you link your instance i can quickly tell you which version you're using. if it's old enough you can also see it on the "about" page.

**Comment by cohm** [comment] 2018-07-20 13:23
Thanks for helping a blind man :)

However, as you suspected this is of limited use (we had a country drop-down in the form, but it seems *zero* registrants filled it, probably because their info is pre-filled since they were logged in when registering):

![screen shot 2018-07-20 at 15 20 39](https://user-images.githubusercontent.com/7143813/43004649-b83b50e2-8c30-11e8-97e2-19d574542042.png)

I'll leave it to you to decide whether there are things that could be improved/expanded or if you think what's there is sufficient (and if so close this issue).

Thanks a lot!

Best,
Christian

**Comment by pferreir** [comment] 2019-06-03 15:43
Duplicate of #3341

**Closed by pferreir** 2019-06-03 15:43 UTC
