### ISSUE TITLE
Review Paper with weights, values and logic 

### ISSUE THREAD

**Issue by Itenium** [indico/indico#2753] opened 2016-12-08 08:54 UTC
Good day.

As part of the review process, it would be great to award a best paper.

As part of this various criteria needs to be added (as is available now) but with the added option of a weight and a value for each of the criteria.

Not all of the criteria will have this, thus only some of the questions will be used as part of this.

A option is thus needed to add the this option. 

At the end a numerical value is then added to the review process, that can then be used to determine the best paper.

If possible these values need then also be exported as a CSV or excel etc file that can be used in various other programs.

Thank you very much for this.

**Comment by pferreir** [comment] 2017-01-31 17:12
Hi,

This seems to be a duplicate of #2797. You can refer to that ticket for a solution.

**Closed by pferreir** 2017-01-31 17:12 UTC
