### ISSUE TITLE
Granular authorization

### ISSUE THREAD

**Issue by deesto** [indico/indico#3871] opened 2019-04-05 18:56 UTC
As far as I can see, from the documentation and from experience, it is not possible to authorize the management of user groups to a member of that group, nor for event or category managers to create and maintain user groups. Would it be possible to implement authorization for groups, a bit more granular than the all-or-nothing method of only the site admin being able to administer user groups?

**Comment by ThiefMaster** [comment] 2019-04-05 18:58
Duplicate of #3040 I think.

**Closed by ThiefMaster** 2019-04-05 18:58 UTC
Labels: duplicate

**Comment by deesto** [comment] 2019-04-05 20:03
Yes, thank you.
