### ISSUE TITLE
Linking "series" of events

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#2056] opened 2015-09-11 07:41 UTC
We have this for lecture series, but it's done in a *very* diry way (link attachments). It would be useful if this was done in a cleaner way (not abusing attachments for it and not being required to do it at creation time).

For example, there could be prev/next buttons for the series similar to what we have for the prev/next event in the event's category. Integration with cloning (option to link the current event (or event series) and its clones into a series of events)

Related snow ticket: CHG33970

**Comment by pferreir** [comment] 2015-09-15 07:35
I believe this is a duplicate of #148. Also related to #1512.

**Closed by pferreir** 2015-09-15 07:35 UTC
Labels: enhancement
