### ISSUE TITLE
1.9.11: add submission rights to subcontribution presenter (as an option)

### ISSUE THREAD

**Issue by jouvin** [indico/indico#3019] opened 2017-07-21 10:29 UTC
If you use subcontributions into your agenda and want to define a presenter for the subcontribution AND give him the submission rights, you have to add him twice: first in the subcontribution (which involves a significant number of clicks!) and second in the contribution protection form. It'd be nice to have button in the subcontribution presenter dialog to give the present the submission rights so that it is automatically added to the list of people able to upload material in the contribution.

**Comment by ThiefMaster** [comment] 2017-07-21 10:29
Duplicate of #2363

**Closed by ThiefMaster** 2017-07-21 10:29 UTC
Labels: duplicate
