### ISSUE TITLE
Provide by *default* mandatory check boxes "Agree to process my personal data" and "Agree to Terms of service" to the conference registration forms

### ISSUE THREAD

**Issue by andriish** [indico/indico#4949] opened 2021-06-15 10:01 UTC
Provide by *default* mandatory check boxes "Agree to process my personal data" and "Agree to Terms of service" to the conference registration forms for a better compliance to  EU GDPR. 

This is crucial.

Best regards,

Andrii

**Comment by ThiefMaster** [comment] 2021-06-15 10:02
I don't think "Terms of Service" are required by GDPR, but explicit consent for data processing makes perfect sense and is indeed something we plan to add as part of the GDPR features listed in the roadmap: https://getindico.io/roadmap/

**Comment by pferreir** [comment] 2021-06-15 12:30
Duplicate of #1415

**Closed** 2021-06-15 12:30 UTC
Labels: enhancement
