### ISSUE TITLE
Material: Allow replacing files while preserving the URL

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#1807] opened 2015-03-23 09:07 UTC
[Suggested in RQF0439318]

- It would make sense if you could replace material with a new file without adding a new record and then deleting the old one. That would already allow you to preserve existing links to the file even if you modify it.

- A step further, which I'm not sure if it's really necessary/important/useful, would be keeping all old versions in the DB and while the current link would point to the latest version, you could also link to older versions somehow (.../material/..../x/filename with x being a version identifier (such as the internal id of the row in the material table))

**Comment by pferreir** [comment] 2015-03-25 17:00
I think there's a ticket on material versioning somewhere.

**Comment by pferreir** [comment] 2015-03-25 17:02
I think someone has already thought of that:

https://github.com/indico/indico/issues/761

**Comment by pferreir** [comment] 2015-03-25 17:06
Duplicate of #761

**Closed by pferreir** 2015-03-25 17:06 UTC
Labels: enhancement, migration
