### ISSUE TITLE
Dependency issue between MarkupSafe and Jinja

### ISSUE THREAD

**Issue by ntim** [indico/indico#2797] opened 2017-01-20 13:42 UTC
Hey,

tried to install indico with easy_install (python 2.7.9), ran into a dependency issue. MarkupSafe 0.15 is requested, but Jinja2>=2.4 leads to installing of 2.9.4 which requires MarkupSafe>=0.23:

```error: MarkupSafe 0.15 is installed but MarkupSafe>=0.23 is required by set(['Jinja2']```

Is there any particular reason why you have the requirements fixed to specific versions? This can interfere with the installed python packages when used on a system not exclusively intended to run indico. 

Thanks in advance

**Comment by ThiefMaster** [comment] 2017-01-20 13:46
You should use a virtualenv to avoid dependency issues - using system/distro packages for Python stuff is rarely a good idea, except in cases where you install a Python tool through your distro's package manager.

Anyway, it's Jinja2 that requires `markupsafe>=0.23` so even if we didn't pin the required version Jinja would still require it.

The reason for us pinning library versions we use directly is that sometimes upgrades break compatibility - even without a major version number change. People using whatever is the latest version available on PyPI at the time of installing results in hard-to-debug issues since we'll have a different Python environment than they do (and even if they provided a `pip freeze` that'd require us to install their versions in a new virtualenv to try to reproduce an issue).

**Comment by ThiefMaster** [comment] 2017-01-20 13:49
Actually, we need to pin Jinja to 2.8.1 in 1.2 or upgrade markupsafe since Flask pulls in the latest Jinja which  is indeed not compatible with our markupsafe requirement. FYI, in master/1.9.x we do specify a Jinja version so there won't be any nasty surprises like this one.

**Comment by ntim** [comment] 2017-01-21 13:15
Maybe it would be good mentioning in the install instructions to use a virtualenv.

**Comment by ThiefMaster** [comment] 2017-01-21 13:18
For 2.0 we will.

Most likely we will even explicitly mention that non-virtualenv setups on normal machines won't be supported - the only place where it kind of makes sense to not use a virtualenv is in a Docker container since that's already a separate environment.

**Comment by ntim** [comment] 2017-01-21 15:38
Looking forward to it :+1:

**Closed** 2017-01-25 16:24 UTC

**Comment by ThiefMaster** [comment] 2017-01-31 17:26
We just released v1.2.1 where this problem is fixed.
