### ISSUE TITLE
Add a way to see what links in event "material" point to

### ISSUE THREAD

**Issue by dguest** [indico/indico#4671] opened 2020-10-26 07:37 UTC
**Is your feature request related to a problem? Please describe.**
A lot of people will upload links under "material". It's very useful to know the context of these links: they often point to other agenda or sites where some simple URL manipulation will give me complementary information. Unfortunately they often point directly at a pdf, which my browser simply downloads without ever telling me where the file came from.

This also seems like a bit of a security concern: if I have no way to verify where some link is pointing I'm forced to blindly follow the link and hope it doesn't go somewhere nasty.

**Describe the solution you'd like**
Either the link should point directly to the destination (rather than something like `https://indico.cern.ch/event/950945/contributions/4071316/attachments/2125382/3578244/go` or there should be some way to get this link which is clearly documented.

**Describe alternatives you've considered**
Tell my colleges not to link directly to pdfs on indico, have faith that no one will ever add a link that points somewhere malicious.

**Comment by ThiefMaster** [comment] 2020-11-11 10:10
duplicate of #4261

**Closed by ThiefMaster** 2020-11-11 10:10 UTC
Labels: enhancement
